name: vga-beta

services:
  app:
    image: "ghcr.io/vidya-gaem-awards/vga-remastered:main"
    environment:
      SSL_MODE: "mixed"
      AUTORUN_ENABLED: true
    env_file: .env.deployment

  cache:
    image: redis:7

networks:
  default:
    name: caddy_net
    external: true
